//! Job-local Default generation state. No model-facing IDs or database storage.

use std::collections::BTreeMap;
use std::sync::Mutex;

use serde::Serialize;

use crate::models::generation_options::GenerationOptions;
use crate::models::learning_item::SourceReference;
use crate::models::note::Note;
use crate::services::chunker::MarkdownChunk;

use super::selection::CandidateAssessment;

/// Unique within a job, including when local chunk indices repeat across notes.
/// This identity is generated by the backend and never sent to a scoring model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct CandidateId {
    source_chunk_index: usize,
    point_position: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct SectionIdentity {
    pub note_path: String,
    pub section_index: usize,
}

/// Text is copied verbatim from Stage A. Full source chunks stay in the job;
/// source_chunk_index is an authoritative reference into that retained array.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KnowledgeCandidate {
    pub id: CandidateId,
    pub note_path: String,
    pub note_title: String,
    pub section: SectionIdentity,
    pub heading: String,
    pub source_chunk_index: usize,
    pub point_position: usize,
    pub knowledge_point: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct NoteContext {
    pub title: String,
    pub section_outline: Vec<String>,
}

/// Options cannot be edited after construction. Stage A registration happens
/// before Stage B, so candidates survive even if subsequent generation fails.
#[derive(Debug)]
pub struct DefaultGenerationJob {
    options: GenerationOptions,
    chunks: Vec<MarkdownChunk>,
    candidates: Mutex<BTreeMap<usize, Vec<KnowledgeCandidate>>>,
    note_contexts: BTreeMap<String, NoteContext>,
    assessments: Mutex<BTreeMap<CandidateId, CandidateAssessment>>,
}

impl DefaultGenerationJob {
    pub fn new(options: GenerationOptions, chunks: Vec<MarkdownChunk>) -> Self {
        let mut note_contexts = BTreeMap::<String, NoteContext>::new();
        let mut sections = std::collections::BTreeSet::new();
        for chunk in &chunks {
            let context = note_contexts
                .entry(chunk.note_path.clone())
                .or_insert_with(|| NoteContext {
                    title: chunk.note_title.clone(),
                    section_outline: Vec::new(),
                });
            if sections.insert((chunk.note_path.clone(), chunk.section_index)) {
                context.section_outline.push(chunk.heading.clone());
            }
        }
        Self {
            options,
            chunks,
            candidates: Mutex::new(BTreeMap::new()),
            note_contexts,
            assessments: Mutex::new(BTreeMap::new()),
        }
    }

    /// Construct the outline once from the note, not from technical chunk splits.
    pub fn with_notes(
        options: GenerationOptions,
        chunks: Vec<MarkdownChunk>,
        notes: &[Note],
    ) -> Self {
        let mut job = Self::new(options, chunks);
        for note in notes {
            let outline = note_outline(&note.content);
            if !outline.is_empty() {
                job.note_contexts.insert(
                    note.path.clone(),
                    NoteContext {
                        title: note.title.clone(),
                        section_outline: outline,
                    },
                );
            }
        }
        job
    }

    pub fn options(&self) -> GenerationOptions {
        self.options
    }

    pub fn chunks(&self) -> &[MarkdownChunk] {
        &self.chunks
    }

    /// Owned candidate handles can be moved into future per-candidate scoring
    /// tasks. The identity and source reference travel with each task's result.
    pub fn candidates(&self) -> Result<Vec<KnowledgeCandidate>, String> {
        let candidates = self
            .candidates
            .lock()
            .map_err(|_| String::from("Candidate state is unavailable"))?;
        Ok(candidates.values().flatten().cloned().collect())
    }

    pub fn note_context(&self, candidate: &KnowledgeCandidate) -> Result<&NoteContext, String> {
        self.note_contexts
            .get(&candidate.note_path)
            .ok_or_else(|| "Candidate note context is unavailable".into())
    }

    pub fn chunk_candidates(
        &self,
        source_chunk_index: usize,
    ) -> Result<Vec<KnowledgeCandidate>, String> {
        Ok(self
            .candidates
            .lock()
            .map_err(|_| "Candidate state is unavailable")?
            .get(&source_chunk_index)
            .cloned()
            .unwrap_or_default())
    }

    pub fn attach_assessment(
        &self,
        candidate: &KnowledgeCandidate,
        assessment: CandidateAssessment,
    ) -> Result<(), String> {
        // Only a backend-owned candidate handle may receive this response.
        self.source_for_candidate(candidate.id)?;
        let mut assessments = self
            .assessments
            .lock()
            .map_err(|_| "Assessment state is unavailable")?;
        if assessments.contains_key(&candidate.id) {
            return Err("Candidate was assessed more than once".into());
        }
        assessments.insert(candidate.id, assessment);
        Ok(())
    }

    pub fn assessments(&self) -> Result<BTreeMap<CandidateId, CandidateAssessment>, String> {
        Ok(self
            .assessments
            .lock()
            .map_err(|_| "Assessment state is unavailable")?
            .clone())
    }

    /// Stage B re-keys a selected subset to kp_1..kp_N. This explicit allocation
    /// maps those local IDs to the original candidates, including skipped points.
    pub fn source_for_selected_point(
        &self,
        selected: &[KnowledgeCandidate],
        point_id: &str,
    ) -> Result<SourceReference, String> {
        let position = point_id
            .strip_prefix("kp_")
            .and_then(|value| value.parse::<usize>().ok())
            .and_then(|value| value.checked_sub(1))
            .filter(|position| point_id == format!("kp_{}", position + 1))
            .ok_or_else(|| "Stage B returned an invalid knowledge point ID".to_string())?;
        let candidate = selected
            .get(position)
            .ok_or_else(|| "Stage B returned an unselected knowledge point ID".to_string())?;
        self.source_for_candidate(candidate.id)
    }

    pub fn register_stage_a(
        &self,
        source_chunk_index: usize,
        points: &[String],
    ) -> Result<(), String> {
        let chunk = self
            .chunks
            .get(source_chunk_index)
            .ok_or_else(|| String::from("Stage A referenced an unknown source chunk"))?;
        let mut candidates = self
            .candidates
            .lock()
            .map_err(|_| String::from("Candidate state is unavailable"))?;
        if candidates.contains_key(&source_chunk_index) {
            return Err(String::from(
                "Stage A candidates are already registered for this chunk",
            ));
        }
        candidates.insert(
            source_chunk_index,
            points
                .iter()
                .enumerate()
                .map(|(point_position, point)| KnowledgeCandidate {
                    id: CandidateId {
                        source_chunk_index,
                        point_position,
                    },
                    note_path: chunk.note_path.clone(),
                    note_title: chunk.note_title.clone(),
                    section: SectionIdentity {
                        note_path: chunk.note_path.clone(),
                        section_index: chunk.section_index,
                    },
                    heading: chunk.heading.clone(),
                    source_chunk_index,
                    point_position,
                    knowledge_point: point.clone(),
                })
                .collect(),
        );
        Ok(())
    }

    /// Preserve the existing Stage B one-based kp_N contract. Neither ordering
    /// of completed tasks nor future scoring IDs participate in this lookup.
    #[cfg(test)]
    pub fn source_for_stage_b(
        &self,
        source_chunk_index: usize,
        point_id: &str,
    ) -> Result<SourceReference, String> {
        let point_position = point_id
            .strip_prefix("kp_")
            .and_then(|value| value.parse::<usize>().ok())
            .and_then(|value| value.checked_sub(1))
            .ok_or_else(|| String::from("Stage B returned an invalid knowledge point ID"))?;
        self.source_for_candidate(CandidateId {
            source_chunk_index,
            point_position,
        })
    }

    /// Future selection/scoring can resolve an owned candidate handle without
    /// relying on model-returned IDs or on the order in which tasks complete.
    pub fn source_for_candidate(&self, id: CandidateId) -> Result<SourceReference, String> {
        let candidates = self
            .candidates
            .lock()
            .map_err(|_| String::from("Candidate state is unavailable"))?;
        let candidate = candidates
            .get(&id.source_chunk_index)
            .and_then(|points| points.get(id.point_position))
            .ok_or_else(|| String::from("Stage B returned an unknown knowledge point ID"))?;
        let chunk = &self.chunks[candidate.source_chunk_index];
        Ok(SourceReference {
            note_path: candidate.note_path.clone(),
            start_line: chunk.start_line,
            end_line: chunk.end_line,
            knowledge_point: candidate.knowledge_point.clone(),
        })
    }
}

fn note_outline(markdown: &str) -> Vec<String> {
    let mut outline = Vec::new();
    let mut fence: Option<(char, usize)> = None;
    for line in markdown.lines() {
        // Four-space indentation is code, including a line that starts with #.
        if line.starts_with("    ") || line.starts_with('\t') {
            continue;
        }
        let line = line.trim_start();
        let first = line.chars().next();
        if matches!(first, Some('`' | '~')) {
            let marker = first.unwrap();
            let count = line
                .chars()
                .take_while(|character| *character == marker)
                .count();
            if count >= 3 {
                match fence {
                    None => fence = Some((marker, count)),
                    Some((open, length))
                        if marker == open && count >= length && line[count..].trim().is_empty() =>
                    {
                        fence = None
                    }
                    _ => {}
                }
                continue;
            }
        }
        if fence.is_some() {
            continue;
        }
        let level = line
            .chars()
            .take_while(|character| *character == '#')
            .count();
        if (1..=6).contains(&level)
            && line
                .as_bytes()
                .get(level)
                .is_some_and(u8::is_ascii_whitespace)
        {
            let heading = line[level..].trim();
            let before_closing = heading.trim_end_matches('#');
            let heading = if before_closing
                .chars()
                .last()
                .is_some_and(char::is_whitespace)
            {
                before_closing.trim_end()
            } else {
                heading
            };
            if !heading.is_empty() {
                outline.push(format!("{} {}", "#".repeat(level), heading));
            }
        }
    }
    outline
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::generation_options::GenerationPurpose;
    use std::collections::BTreeSet;
    use std::sync::Arc;

    fn chunk(note: &str, section_index: usize, chunk_index: usize) -> MarkdownChunk {
        MarkdownChunk {
            note_path: format!("notes/{note}.md"),
            note_title: note.to_string(),
            heading: format!("Section {section_index}"),
            content: "Original source content".to_string(),
            section_index,
            chunk_index,
            start_line: 10 + chunk_index * 5,
            end_line: 14 + chunk_index * 5,
        }
    }

    #[test]
    fn job_options_are_captured_independently_of_later_settings() {
        let mut settings: GenerationOptions =
            serde_json::from_str(r#"{"max_learning_items":7,"purpose":"foundations"}"#).unwrap();
        let job = DefaultGenerationJob::new(settings, vec![]);
        settings =
            serde_json::from_str(r#"{"max_learning_items":100,"purpose":"explanations"}"#).unwrap();
        assert_eq!(settings.max_learning_items(), 100);
        assert_eq!(job.options().max_learning_items(), 7);
        assert_eq!(job.options().purpose(), GenerationPurpose::Foundations);
    }

    #[test]
    fn note_outline_keeps_nested_and_repeated_headings_without_code_or_chunk_duplication() {
        let note = Note {
            id: None, path: "notes/first.md".into(), title: "Subject".into(), last_modified: "0".into(),
            content: "# Subject\n## Repeated\n### Detail\n```md\n# Not a section\n```\n## Repeated\n~~~~md\n## Also code\n~~~~\n## Learn C#\n## Closed heading ##\n    # Indented code".into(),
        };
        let job = DefaultGenerationJob::with_notes(
            GenerationOptions::default(),
            vec![chunk("first", 0, 0), chunk("first", 0, 1)],
            &[note],
        );
        job.register_stage_a(0, &["Knowledge".into()]).unwrap();
        let point = job.candidates().unwrap().remove(0);
        assert_eq!(
            job.note_context(&point).unwrap().section_outline,
            [
                "# Subject",
                "## Repeated",
                "### Detail",
                "## Repeated",
                "## Learn C#",
                "## Closed heading"
            ]
        );
    }

    #[test]
    fn rekeyed_selected_points_keep_original_positions_and_sources() {
        let job =
            DefaultGenerationJob::new(GenerationOptions::default(), vec![chunk("first", 0, 0)]);
        job.register_stage_a(
            0,
            &[
                "Original first".into(),
                "  Original second\nwith code  ".into(),
                "Original third".into(),
            ],
        )
        .unwrap();
        let candidates = job.candidates().unwrap();
        let selected = vec![candidates[1].clone(), candidates[2].clone()];
        assert_eq!(
            job.source_for_selected_point(&selected, "kp_1")
                .unwrap()
                .knowledge_point,
            candidates[1].knowledge_point
        );
        assert_eq!(
            job.source_for_selected_point(&selected, "kp_2")
                .unwrap()
                .knowledge_point,
            candidates[2].knowledge_point
        );
        for id in ["kp_0", "kp_3", "kp_01", "kp_1.0", "candidate-1"] {
            assert!(job.source_for_selected_point(&selected, id).is_err());
        }
    }

    #[test]
    fn candidates_preserve_identity_metadata_text_and_original_chunk_references() {
        let job = DefaultGenerationJob::new(
            GenerationOptions::default(),
            vec![
                chunk("first", 2, 0),
                chunk("first", 2, 1),
                chunk("second", 2, 0),
            ],
        );
        let points = vec![
            "  ATP → energy\nwith `code`  ".to_string(),
            "Same text".to_string(),
        ];
        for index in [2, 0, 1] {
            job.register_stage_a(index, &points).unwrap();
        }
        let candidates = job.candidates.lock().unwrap();
        let ids = candidates
            .values()
            .flatten()
            .map(|candidate| candidate.id)
            .collect::<BTreeSet<_>>();
        assert_eq!(ids.len(), 6);
        for (index, batch) in candidates.iter() {
            let source = &job.chunks()[*index];
            for (position, candidate) in batch.iter().enumerate() {
                assert_eq!(candidate.note_path, source.note_path);
                assert_eq!(candidate.note_title, source.note_title);
                assert_eq!(candidate.section.note_path, source.note_path);
                assert_eq!(candidate.section.section_index, source.section_index);
                assert_eq!(candidate.heading, source.heading);
                assert_eq!(candidate.source_chunk_index, *index);
                assert_eq!(candidate.point_position, position);
                assert_eq!(candidate.knowledge_point, points[position]);
                assert_eq!(
                    job.chunks()[candidate.source_chunk_index].chunk_index,
                    source.chunk_index
                );
                assert_eq!(
                    job.chunks()[candidate.source_chunk_index].content,
                    "Original source content"
                );
            }
        }
        assert_ne!(candidates[&0][0].section, candidates[&2][0].section);
    }

    #[tokio::test]
    async fn out_of_order_candidate_tasks_keep_their_source_association() {
        let job = Arc::new(DefaultGenerationJob::new(
            GenerationOptions::default(),
            vec![chunk("first", 0, 0), chunk("second", 1, 0)],
        ));
        job.register_stage_a(0, &["First point".to_string()])
            .unwrap();
        job.register_stage_a(1, &["Second point".to_string()])
            .unwrap();
        let candidates = job.candidates().unwrap();
        let (release, wait) = tokio::sync::oneshot::channel::<()>();
        let mut tasks = tokio::task::JoinSet::new();
        let first = candidates[0].clone();
        tasks.spawn(async move {
            wait.await.unwrap();
            (first, 3)
        });
        let second = candidates[1].clone();
        tasks.spawn(async move { (second, 5) });
        let (candidate, assessment) = tasks.join_next().await.unwrap().unwrap();
        assert_eq!(candidate.id, candidates[1].id);
        assert_eq!(assessment, 5);
        assert_eq!(
            job.source_for_candidate(candidate.id).unwrap().note_path,
            "notes/second.md"
        );
        release.send(()).unwrap();
        let (candidate, assessment) = tasks.join_next().await.unwrap().unwrap();
        assert_eq!(candidate.id, candidates[0].id);
        assert_eq!(assessment, 3);
        assert_eq!(
            job.source_for_candidate(candidate.id)
                .unwrap()
                .knowledge_point,
            "First point"
        );
    }

    #[test]
    fn stage_b_ids_map_to_original_positions_and_reject_unknown_ids() {
        let job =
            DefaultGenerationJob::new(GenerationOptions::default(), vec![chunk("first", 0, 1)]);
        let points = vec![
            "First point".to_string(),
            "Second point".to_string(),
            "Third point".to_string(),
        ];
        job.register_stage_a(0, &points).unwrap();
        let source = job.source_for_stage_b(0, "kp_3").unwrap();
        assert_eq!(source.note_path, "notes/first.md");
        assert_eq!(source.start_line, 15);
        assert_eq!(source.end_line, 19);
        assert_eq!(source.knowledge_point, points[2]);
        for id in ["kp_0", "kp_4", "candidate-0", "kp_-1", "kp_1.5"] {
            assert!(job.source_for_stage_b(0, id).is_err());
        }
        assert!(job.source_for_stage_b(1, "kp_1").is_err());
        assert!(job.register_stage_a(0, &points).is_err());
        assert!(job.register_stage_a(1, &points).is_err());
    }
}
