import { useEffect, useState } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { ChevronDown } from 'lucide-react'

type Question = {
  id: number
  question: string
  option_a: string
  option_b: string
  option_c: string
  option_d: string
  correct_answer: string
  explanation: string | null
  model: string | null
}

export function QuestionsPage() {
  const [questions, setQuestions] = useState<Question[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')
  const [expandedIds, setExpandedIds] = useState<number[]>([])

  const toggleExpanded = (id: number) => {
    setExpandedIds((current) =>
      current.includes(id) ? current.filter((item) => item !== id) : [...current, id],
    )
  }

  const isCorrectOption = (choice: string, label: 'A' | 'B' | 'C' | 'D', q: Question) => {
    const answer = q.correct_answer.trim().toLowerCase()
    const normalizedChoice = choice.trim().toLowerCase()
    const normalizedLabel = label.toLowerCase()

    return (
      answer === normalizedLabel ||
      answer === `option_${normalizedLabel}` ||
      answer === normalizedChoice
    )
  }

  useEffect(() => {
    const loadQuestions = async () => {
      setIsLoading(true)
      setError('')

      try {
        const rows = await invoke<Question[]>('get_questions')
        setQuestions(rows)
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Failed to load questions'
        setError(message)
      } finally {
        setIsLoading(false)
      }
    }

    void loadQuestions()
  }, [])

  return (
    <div className="app-container questions-page">
      <header className="settings-panel">
        <h1>Questions</h1>
        <p className="settings-help-text">
          Showing all saved question records.
        </p>
      </header>

      {error && <div className="error-banner">{error}</div>}

      {isLoading ? (
        <section className="settings-panel">
          <p className="settings-help-text">Loading questions...</p>
        </section>
      ) : questions.length === 0 ? (
        <section className="settings-panel">
          <p className="settings-help-text">No questions found.</p>
        </section>
      ) : (
        <section className="questions-list" aria-label="Questions list">
          {questions.map((item) => (
            <article className="question-card" key={item.id}>
              <button
                type="button"
                className="question-toggle"
                onClick={() => toggleExpanded(item.id)}
                aria-expanded={expandedIds.includes(item.id)}
                aria-controls={`question-details-${item.id}`}
              >
                <div className="question-summary">
                  <span className="question-id">#{item.id}</span>
                  <h2>{item.question}</h2>
                </div>
                <ChevronDown
                  className={`question-chevron${expandedIds.includes(item.id) ? ' is-open' : ''}`}
                  aria-hidden="true"
                />
              </button>

              {expandedIds.includes(item.id) && (
                <div className="question-details" id={`question-details-${item.id}`}>
                  <ul className="question-options">
                    {[
                      { key: 'A' as const, value: item.option_a },
                      { key: 'B' as const, value: item.option_b },
                      { key: 'C' as const, value: item.option_c },
                      { key: 'D' as const, value: item.option_d },
                    ].map((option) => (
                      <li
                        key={option.key}
                        className={`question-option${isCorrectOption(option.value, option.key, item) ? ' is-correct' : ''}`}
                      >
                        <span className="question-option-key">{option.key}</span>
                        <span>{option.value}</span>
                      </li>
                    ))}
                  </ul>

                  <p className="question-model">
                    Generated by: {item.model ?? 'Unknown model'}
                  </p>
                </div>
              )}
            </article>
          ))}
        </section>
      )}
    </div>
  )
}